config/routes.rb
Rails.application.routes.draw do
  resources :maps, only: [:index, :new, :create, :show]
  resources :about, only: [:index]
  root 'maps#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  belongs_to :map
end

app/models/map.rb
class Map < ApplicationRecord
  has_many :cities, dependent: :destroy

  before_save :sanitize_svg

  def parse_cities
    nodes = Nokogiri::XML self.svg
    city_names = nodes.css("text.city")
    city_stats = nodes.css("circle.city")
    cities = {}
    city_names.each_with_index do |city, idx|
      cities[city.text] = {}
      cities[city.text][:population] = city_stats[idx].attributes["r"].value.to_i
      cities[city.text][:color] = city_stats[idx].attributes["style"].value.match(/fill:\s(\w+);.+/)[1]
    end

    return cities
  end

  def save_cities
    if self.cities.blank?
      new_cities = parse_cities
      City.transaction do
        new_cities.each do |name, stats|
          cities.create!(name: name, population: stats[:population], color: stats[:color] )
        end
      end
    end
    cities
  end

  private

    def sanitize_svg
      unsafe_svg   = Nokogiri::XML(self.svg)
      xslt  = Nokogiri::XSLT(File.read(File.join(Rails.root,'/lib/assets/safe_svg.xslt')))
      self.svg = xslt.transform(unsafe_svg)
    end
end

app/controllers/about_controller.rb
class AboutController < ApplicationController

  def index
    #code
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController

  def index
    @maps = Map.all
  end

  def show
    @map = Map.find(params[:id])
  end

  def new
    @map = Map.new
  end

  def create
    if @map = Map.create(map_params)
      @map.save_cities
      redirect_to map_path(@map), :notice => "Map was saved"
    else
      render :new, :error => "Map save failed!"
    end
  end

  private

    def map_params
      params.require(:map).permit(:utf8, :authenticity_token, :name, :description, :svg)
    end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/about/index.html.haml
.core-template
  %h1
    Welcome to MapMaker v1.0
  .main-content
    %p.text-left
      While using another map making program for a Godbound game I'm running, I
      realized I really wanted a mapping system that didn't limit me to hexes,
      and could randomly generate new terrains with some sort of logic to them.
      Mountains creating lush forests on the side facing the ocean, and deserts
      on the other, for example. While I'm a web developer by trade, that sort
      of climate simulation math is beyond anything I've done before, so I wasn't
      really expecting I'd be able to do it any time soon.
    %p.text-left
      That was when I ran across an article on National Geographic where
      %a{href: 'https://mewo2.com/notes/terrain/', target: '_blank'}
        Martin O'Leary
      explained how he built the maps for his Twitter bot,
      %a{href: 'https://twitter.com/unchartedatlas', target: '_blank'}
        @unchartedatlas
      , and since he open sourced his code, it seemed like a great starting point
      for what I wanted to do. So I built this site, made some changes and tweaks,
      and open sourced it on
      %a{href: 'https://github.com/nextekcarl/Mapmaker', target: '_blank'}
        Github.

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MapMaker</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://d3js.org/d3.v4.js"></script>
  </head>

  <body>
    <nav class="navbar navbar-fixed-top navbar-dark bg-inverse">
      <a class="navbar-brand" href="/">Map Maker</a>
      <ul class="nav navbar-nav">
        <li class="nav-item<%= ' active' if request.fullpath == '/' || request.fullpath == maps_path %>">
          <%= link_to 'Maps <span class="sr-only">(current)</span>'.html_safe, maps_path, class: 'nav-link' %>
        </li>
        <li class="nav-item<%= ' active' if request.fullpath == new_map_path %>">
          <%= link_to 'New Map'.html_safe, new_map_path, class: 'nav-link' %>
        </li>
        <li class="nav-item<%= ' active' if request.fullpath == about_index_path %>">
          <%= link_to 'About'.html_safe, about_index_path, class: 'nav-link' %>
        </li>
      </ul>
    </nav>
    <div class="container">
      <%= image_tag "ajax-loader.gif", id: 'loading-indicator', style: 'display:none' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/maps/index.html.haml
.core-template
  %h1
    Welcome to MapMaker v1.0
  .sidebar
    %p
      This is the list of every map saved with this system. Eventually I'll add
      methods to edit region names and cities, add descriptions and such to them
      but for now this will do.
  .main-content
    %table.table-striped.table-bordered.table-hover
      %tbody
        %tr
          %th
            id
          %th
            name
          %th
            description
        -@maps.each do |map|
          %tr
            %td
              =map.id
            %td
              =link_to map.name, map_path(map)
            %td
              =truncate(map.description, length: 50)

app/views/maps/new.html.haml
.core-template
  %h1
    Welcome to MapMaker v1.0
  .sidebar
    %p
      You can toggle the visibility of the region names and cities, in case they are covering up
      something interesting, but they will be saved in either case.
    %p
      You can also click on a name to change it before saving it. After that it becomes more difficult to change.
      In the same way, you can change the size of a city by clicking on the circle.

  %button{id: 'generate-map'} Generate Map
  %button{id: 'toggle-regions'} Toggle Regions
  %button{id: 'toggle-cities'} Toggle Cities
  %button{id: 'toggle-rivers'} Toggle Rivers
  %button{id: 'save-map'} Save map

  .main-content
    .form{id: 'map-form'}
      =form_for(@map) do |f|
        =f.label :name
        =f.text_field :name
        %br
        =f.label :description
        =f.text_area :description
    .new-map
      %svg{width: "800", id: 'map'}

app/views/maps/show.html.haml
- if @map.island?
  %style{:type => "text/css"}
    ='path.coast {fill: white;}'.html_safe
    ='svg {background-color: blue;}'.html_safe
.core-template
  %h1
    =@map.name
  .sidebar
    %p
      %table.table-striped.table-bordered.table-hover.table-centered
        %tbody
          %tr
            %th
              name
            %th
              pop
            %th
              color
          -@map.cities.each do |city|
            %tr{class: "x-highlight-city", data: {city: "#{city.name}"}}
              %td
                =city.name
              %td
                =city.population
              %td{style: "background: #{city.color}"}
      =@map.description
  .main-content
    %button{id: 'toggle-regions'} Toggle Regions
    %button{id: 'toggle-cities'} Toggle Cities
    %button{id: 'toggle-rivers'} Toggle Rivers

    =@map.svg.html_safe